# Generated by Django 5.2.8 on 2025-11-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('TO_DO', 'to_do'), ('DONE', 'done'), ('IN_PROGRESS', 'in_progress')], default='TO_DO', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
